### ISSUE TITLE
.NET Core 1.1

### ISSUE THREAD

**Issue by luylucas10** [pengweiqhca/Xunit.DependencyInjection#10]
It is not a issue, I need some help.
I have many projects that use .NET Core 1.1 and this cannot be change because we use VS 2015. Projects have a Tests class library with XUnit, but this package (dependency injection) is not compatible with our version.
Which version of this package is compatible with .NET Core 1.1? Or Which solution can I build to have compatibility?
Thanks

**Comment by pengweiqhca** [comment]
You can use [Xunit.DependencyInjection 4.4](https://www.nuget.org/packages/Xunit.DependencyInjection/4.4.0), but i was not test.
