### ISSUE TITLE
AddXunitOutput for logging is not available.

### ISSUE THREAD

**Issue by brandonh-msft** [pengweiqhca/Xunit.DependencyInjection#104]
I'm using v 8.9.0 of the library, and I cannot configure logging for the Xunit TestOutput target as shown in docs & samples:

![image](https://github.com/pengweiqhca/Xunit.DependencyInjection/assets/20270743/4b95f173-4f51-419a-afca-921e4bb187db)

**Comment by WeihanLi** [comment]
The logging feature is in the package `Xunit.DependencyInjection.Logging`, and for `AspNetCoreTesting` you need a reference for the `Xunit.DependencyInjection.AspNetCoreTesting` package
