### ISSUE TITLE
xUnit104 Fixture argument 'xyz' does not have a fixture source

### ISSUE THREAD

**Issue by marklauter** [pengweiqhca/Xunit.DependencyInjection#108]
**Describe the bug**
Xunit.DependencyInjection seems to be incompatible with xUnit 2.6.3. I receive this error after upgrading from xUnit 2.6.2

Error	xUnit1041	Fixture argument 'pool' does not have a fixture source (if it comes from a collection definition, ensure the definition is in the same assembly as the test)	Pool.Tests	

**To Reproduce**
with XUnit.DI 8.9.0 and xUnit 2.6.2 everything works normally.
with XUnit.DI 8.9.0 and xUnit 2.6.3 everything works normally, I get the fixture error.
https://xunit.net/xunit.analyzers/rules/xUnit1041

This is my unit test

```
namespace Pool.Tests;

public sealed class PoolTests(IPool<IEcho> pool) // <-- error is here 
{
    [Fact]
    public void PoolInjected()
    {
        Assert.NotNull(pool);
    }
}
```

This is my startup

```
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;

namespace Pool.Tests;

public sealed class Startup
{
    private readonly IConfiguration configuration;

    public Startup()
    {
        configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(new Dictionary<string, string>
            {
                { "PoolOptions:MinSize", "10" },
                { "PoolOptions:MaxSize", "20" }
            })
            .Build();
    }

    public void ConfigureServices(IServiceCollection services)
    {
        _ = services.AddTransient<IEcho, Echo>();
        _ = services.AddPool<IEcho>(configuration);
    }
}
```

**Expected behavior**
expected behavior is no error when upgrading to xunit 2.6.3.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version:
 Xunit.DependencyInjection 8.9.0
 xUnit 2.6.3

**Additional context**
I understand that this might be an issue with xUnit, and if it is I'm hoping you can give me some ideas for the ticket I submit there.

**Comment by pengweiqhca** [comment]
Upgrade `Xunit.DependencyInjection` to 8.9.1 or add the below code to project file.

``` xml
  <PropertyGroup>
    <NoWarn>$(NoWarn);xUnit1041</NoWarn>
  </PropertyGroup>
```
