### ISSUE TITLE
How to inject my own IConfiguration

### ISSUE THREAD

**Issue by vd3d** [pengweiqhca/Xunit.DependencyInjection#11]
Hi,

I try to test a class and this one uses some code like this one :

`_context.Configuration.GetValue<int>("settings:archiveUnarchivablePeriod");`

Where _context is of type HostBuilderContext.

For every test I need a few specific set of settings, how can I set the 'Configuration' property from my unit test ?

Thanks

**Comment by pengweiqhca** [comment]
``` C#
public class SomeTestClass(IConfiguration configuration)
{
}
```

https://github.com/dotnet/extensions/blob/master/src/Hosting/Hosting/src/HostBuilder.cs#L199
https://github.com/dotnet/extensions/blob/master/src/Hosting/Hosting/src/HostBuilder.cs#L211

**Comment by pengweiqhca** [comment]
https://github.com/pengweiqhca/Xunit.DependencyInjection#how-to-inject-iconfiguration-or-ihostingenvironment-into-startup
