### ISSUE TITLE
Member 'ConfigureServices' does not access instance data and can be marked as static (CA1822)

### ISSUE THREAD

**Issue by glen-84** [pengweiqhca/Xunit.DependencyInjection#110]
**Solutions**

Library:

1. Add a diagnostic suppressor for the `Startup` class. ([example](https://github.com/dotnet/roslyn-analyzers/blob/48e7c8f02b8e38e3bba0411923a904f25e9bf1a0/src/Roslyn.Diagnostics.Analyzers/Core/RelaxTestNamingSuppressor.cs))
2. Add an interface that the `Startup` class can implement.

Developer:

1. Disable inline – looks very messy.
    ```cs
    #pragma warning disable CA1822 // Mark members as static
        public void ConfigureServices(IServiceCollection services)
    #pragma warning restore CA1822 // Mark members as static
        {
    ```
2. Disable in `.editorconfig` – applies to the whole file.
    ```ini
    [Startup.cs]
    dotnet_diagnostic.CA1822.severity = none
    ```

**Comment by pengweiqhca** [comment]
Allow static

**Comment by glen-84** [comment]
Oh! I didn't realize that. Thank you. 🙂
