### ISSUE TITLE
Support MaxParallelThreads 

### ISSUE THREAD

**Issue by chrisdreams13** [pengweiqhca/Xunit.DependencyInjection#111]
**Add MaxParallelThreads support when ParallelizationMode = Force/Enhance**
I activated the ParallelizationMode=Force/Enhance and run my integration tests. But some tests result in "Execution Timeout Expired".

I have about 500 tests with 3 seconds to complete each one, each test calls a wait from an static SemaphoreSlim(1, 1) to perform a db insertion (must be run one at time, about 1 sec) and then continue with a complex extraction of the db and compare it to a file (this could be run in parallel, about 2 secs). The problem is the 300th test should wait the others to release the semaphore and run, but result in an "Execution Timeout Expired" exception.

I would like to control how many threads are running in order to last threads won't be running for long time resulting in timeout.

**Add MaxParallelThreads support**
Please considere the using of MaxParallelThreads or another config to control how many threads are running at time and avoid long waiting.

**Comment by pengweiqhca** [comment]
Maybe you can try `[assembly: CollectionBehavior(MaxParallelThreads = n)]`.

More, please see [xunit parallelism Default Behavior](https://xunit.net/docs/running-tests-in-parallel#parallelism-in-test-frameworks).

**Comment by chrisdreams13** [comment]
I tried to replicate it in a clean project and [assembly: CollectionBehavior(MaxParallelThreads = n)] works well, I need to check why in my full project is running all at same time.

Thanks a lot.

**Comment by chrisdreams13** [comment]
Hi, finally I could reproduce the error. I downloaded your full repo and added more InlineData to **ParallelTheoryTests.Theory** function. All tests result in "Assert.Equal() Failure: Values differ Expected: 2 Actual: 9".

ConcurrencyFixture adds 1 to the actual value (which is returned) and then reduces it, but as the tests are not limit to **MaxParallelThreads** value all tests runs at same time. I could manage it with SemaphoreSlim but as some Tests are waiting for firsts to finish an Execution Timeout Expired is thrown.

```C#
using Xunit;

// check CollectionBehavior isn't duplicated in TestOutputHelperTests
[assembly: CollectionBehavior(DisableTestParallelization = false, MaxParallelThreads = 2)] 

namespace Xunit.DependencyInjection.Test.Parallelization;

public class ParallelTheoryTests(ConcurrencyFixture fixture) : IClassFixture<ConcurrencyFixture>
{
    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    [InlineData(3)]
    [InlineData(4)]
    [InlineData(5)]
    [InlineData(6)]
    [InlineData(7)]
    [InlineData(8)]
    [InlineData(9)]
    public async Task Theory(int _) => Assert.Equal(2, await fixture.CheckConcurrencyAsync());
}
```

**Comment by pengweiqhca** [comment]
Upgrade Xunit.DependencyInjection to 9.3.0, xunit to 2.8.0

**Comment by chrisdreams13** [comment]
It was difficult to test it directly in your repository (not so sure how to set xunit 2.8.0), I created a separated project with the ParallelTheoryTests and works perfect, thank you so much.
