### ISSUE TITLE
Plans to support the new .NET 8 DI KeyedServices?

### ISSUE THREAD

**Issue by amarinov-taurex** [pengweiqhca/Xunit.DependencyInjection#118]
As the title says - are there any plans to support the new .NET 8 KeyedServices?

I tried it out with the Keyed service registrations, but it seems that the TestFramework does not take the [FromKeyedService] attribute into account as of now.

P.S. Thank you for the awesome DI integration framework!

**Comment by pengweiqhca** [comment]
Upgrade [Xunit.DependencyInjection] to `9.1.0`.
