### ISSUE TITLE
Parallel tests are not working when CollectionAtribute is used.

### ISSUE THREAD

**Issue by chrisdreams13** [pengweiqhca/Xunit.DependencyInjection#119]
**Describe the bug**
Parallel tests are not working when CollectionAtribute is used.

**To Reproduce**
Adding CollectionAttribute to example code.
```C#
namespace Xunit.DependencyInjection.Test.Parallelization;

[CollectionDefinition(nameof(Collection), DisableParallelization = false)]
public class Collection;

[Collection(nameof(Collection))]
public class ParallelTheoryTests(ConcurrencyFixture fixture) : IClassFixture<ConcurrencyFixture>
{
    [Theory]
    [InlineData(1)]
    [InlineData(2)]
    public async Task Theory(int _) => Assert.Equal(2, await fixture.CheckConcurrencyAsync());
}
```
**Expected behavior**
Parallel test should run with and without CollectionAttribute.

**Desktop:**
 - OS: Win10
 - Net: 8.0.0
 - Xunit.DependencyInjection: 9.1.0

**Comment by pengweiqhca** [comment]
> If [`[Collection]`](https://github.com/xunit/xunit/issues/1227#issuecomment-297131879), `[CollectionDefinition(DisableParallelization = true)]`, `[DisableParallelization]` declared on the test class, the test class will run sequentially.

I will change the behavior if `ParallelizationMode` is `Force`

**Comment by pengweiqhca** [comment]
9.2.0

**Comment by chrisdreams13** [comment]
Works so well, thanks a lot.
