### ISSUE TITLE
A bout real time discovery

### ISSUE THREAD

**Issue by Hsu-Cheng-Wei** [pengweiqhca/Xunit.DependencyInjection#12]
Hello, I use this extension,that is great,but I found a question, that real time discovery of test explorer not working when I assign framework from xunit to DependencyInjectionTestFramework, if any idea to resolve it?

Thank you

**Comment by pengweiqhca** [comment]
I not found any problem in `Xunit.DependencyInjection.Test`
https://docs.microsoft.com/en-us/visualstudio/test/live-unit-testing-faq
