### ISSUE TITLE
Support for property injection

### ISSUE THREAD

**Issue by michaeltg17** [pengweiqhca/Xunit.DependencyInjection#120]
Usually you have dependencies in the constructor of each test class like this:

```
public class MyTestClass(IDependency dependency, ITestOutputHelper testOutputHelper) : MyTestBase(dependency, testOutputHelper)
{
   [Fact]
   public void SomeTest()
   {
   }
}
```

But sometimes you only use them in the base class so the ideal code would look like this:

```
public class MyTestClass : MyTestBase
{
   [Fact]
   public void SomeTest()
   {
   }
}
```

To achive this, having support for property injection would be nice.

In this project you can have it: https://github.com/flavien/quickwire

The problem is that the test class is created outside the DI container and its dependencies passed manually (only constructor's ones).

I think it won't be hard to add support for property injection as the main work is already done.

**Comment by pengweiqhca** [comment]
Supported at 9.2.0

See [demo](https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/9.2.0/test/Xunit.DependencyInjection.Test/BeforeAfterTestTest.cs)

**Comment by michaeltg17** [comment]
Hi.

I tried it but it only works with services registered in the Startup class or the ITestOutputHelperAccessor.

I have an scenario in which I need something like this:

```
public class BeforeAfterTestConfiguration(WebApplicationFactoryFixture webApplicationFactoryFixture, ITestOutputHelper testOutputHelper)
    : BeforeAfterTest
{
    public override void Before(object? testClassInstance, MethodInfo methodUnderTest)
    {
        if (testClassInstance is Test test)
        {
            test.WebApplicationFactoryFixture = webApplicationFactoryFixture;
            test.TestOutputHelper = testOutputHelperAccessor.Output;
            test.Initialize();
        }
    }
}
```

These parameters (fixture and test output) are injected fine in the current running test class but not in this BeforeAfterTest class.

**Comment by pengweiqhca** [comment]
1. TestFixture is xunit feature, you must register it as a (keyed) service.

2. ITestOutputHelper => ITestOutputHelperAccessor

**Comment by michaeltg17** [comment]
How would you register it? Okay keyed but what lifetime and what key? I'm not able to see how it would work.

In my case the fixture has an IMessageSink parameter as well.

`WebApplicationFactoryFixture(IMessageSink messageSink)`

Okay with point 2.

**Comment by pengweiqhca** [comment]
`services.AddScoped<WebApplicationFactoryFixture>()`, `public class BeforeAfterTestConfiguration(WebApplicationFactoryFixture webApplicationFactoryFixture)`
or
`services.AddKeyedSingleton<WebApplicationFactoryFixture>(KeyedService.AnyKey)`, `public class BeforeAfterTestConfiguration([FromKeyedServices("someKey")]WebApplicationFactoryFixture webApplicationFactoryFixture)`

**Comment by michaeltg17** [comment]
Okay, it works perfectly. Thanks!
