### ISSUE TITLE
Service Provider object is becoming null while running the script through commandline

### ISSUE THREAD

**Issue by kjakkam** [pengweiqhca/Xunit.DependencyInjection#121]
In Startup.cs file, created an object for ServiceProvider as below

services.AddSingleton<IRestLibrary, RestLibrary>();
IServiceProvider serviceProvider;
serviceProvider = services.BuildServiceProvider();

During, any of other methods execution in that same Project, trying to get the data of serviceProvider. But that serviceProvider's data is showing as null.

The issue is only happening through the commandline execution. If we try to execute the same scenario through Visual Studio, it is working fine without any issues.

**Comment by pengweiqhca** [comment]
Can you give us any more information? such as a demo?

**Comment by kjakkam** [comment]
Sure, I will create a sample project, and share the details.

**Comment by kjakkam** [comment]
@pengweiqhca, I have created a demo project, and in which the issue reproducing.

Please go through the below demo project
https://github.com/jakkamk4/XUnitTestAutomation

**Issue:** 
From CommandPrompt, go to following project execution Path - bin\Debug\net6.0 folder
Execute below command - It will execute - "GetLocationOfTestEmployee" Test case
**dotnet test TestProject1.dll**

While executing the test case through Comman Prompt, it is throwing System.NullReferenceException at ServiceLocator.cs:line 35
**i.e. IServiceProvider is getting null**

If we execute same test case through Visaul studio, it is executing successfully. The issue is only with CommandPrompt execution

**Comment by pengweiqhca** [comment]
Please use [MethodData], more see [[MemberData] how to inject?](https://github.com/pengweiqhca/Xunit.DependencyInjection?tab=readme-ov-file#memberdata-how-to-inject)

**Comment by kjakkam** [comment]
> Please use [MethodData], more see [[MemberData] how to inject?](https://github.com/pengweiqhca/Xunit.DependencyInjection?tab=readme-ov-file#memberdata-how-to-inject)

@pengweiqhca , seeing below error after replacing the [MemberData] attribute with [MethodData] attribute (ex:  [MethodData(nameof(TestData<Location>.GetLocationObject))])


Error message after running the test case:
   System.NotSupportedException : Specified method is not supported.

**Comment by kjakkam** [comment]
> > Please use [MethodData], more see [[MemberData] how to inject?](https://github.com/pengweiqhca/Xunit.DependencyInjection?tab=readme-ov-file#memberdata-how-to-inject)
> 
> @pengweiqhca , seeing below error after replacing the [MemberData] attribute with [MethodData] attribute (ex: [MethodData(nameof(TestData.GetLocationObject))])
> 
> Error message after running the test case: System.NotSupportedException : Specified method is not supported.

@pengweiqhca ,One observation, through command prompt execution, I assumed that - Startup file is not being called first.

**Comment by pengweiqhca** [comment]
Fix https://github.com/jakkamk4/XUnitTestAutomation/pull/1

**Comment by kjakkam** [comment]
> Fix [jakkamk4/XUnitTestAutomation#1](https://github.com/jakkamk4/XUnitTestAutomation/pull/1)

@pengweiqhca , Thank you for providing the fix details. It was executing successfully through Command Line and Visual Studio without any issues.
