### ISSUE TITLE
请教一下TestFramework  为什么可以继承，研究源码不太明白

### ISSUE THREAD

**Issue by wuzxc1230123** [pengweiqhca/Xunit.DependencyInjection#127]
我在A类库里面重写了XunitTestFramework  添加了assembly: TestFramework特性，但是B类库引用类库后没有启动A类库的重写XunitTestFramework   可以问问大佬是怎么实现的TestFramework特性可以继承的吗

**Comment by WeihanLi** [comment]
打包时会打包一个 targets 文件会在引用 package 的项目里尝试自动添加 attribute

https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/main/src/Xunit.DependencyInjection/Xunit.DependencyInjection.csproj#L46

**Comment by wuzxc1230123** [comment]
<ItemGroup>
    <AssemblyAttribute Include="Xunit.TestFramework"
                       Condition="'$(EnableXunitDependencyInjectionDefaultTestFrameworkAttribute)' == '' OR '$(EnableXunitDependencyInjectionDefaultTestFrameworkAttribute)' == 'true'">
      <_Parameter1 Condition="'$(ParallelizationMode)' != 'true' AND '$(ParallelizationMode)' != 'enhance' AND '$(ParallelizationMode)' != 'force'">Xunit.DependencyInjection.DependencyInjectionTestFramework</_Parameter1>
      <_Parameter1 Condition="'$(ParallelizationMode)' == 'true' OR '$(ParallelizationMode)' == 'enhance'">Xunit.DependencyInjection.DependencyInjectionEnhancedParallelizationTestFramework</_Parameter1>
      <_Parameter1 Condition="'$(ParallelizationMode)' == 'force'">Xunit.DependencyInjection.DependencyInjectionForcedParallelizationTestFramework</_Parameter1>
      <_Parameter2>Xunit.DependencyInjection</_Parameter2>
    </AssemblyAttribute>

  
  </ItemGroup>

我的表述有点问题，我不太理解为什么我代码加了这段可以 DependencyInjectionTestFramework没有自动启动，而大佬的代码可以自动启动

**Comment by pengweiqhca** [comment]
如果是通过项目引用时，需要[手动引用 target 文件](https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/main/test/Xunit.DependencyInjection.Test/Xunit.DependencyInjection.Test.csproj#L12)

**Comment by wuzxc1230123** [comment]
谢谢大佬，懂了
