### ISSUE TITLE
How to inject my IConfiguration to the Startup class?

### ISSUE THREAD

**Issue by ayberkcanturk** [pengweiqhca/Xunit.DependencyInjection#13]
I need to inject IConfiguration to the start up class to pass the options to the registrations. You can do this in ASP.NET Core easily. 

> Only the following service types can be injected into the Startup constructor when using the Generic Host (IHostBuilder):
> 
> IWebHostEnvironment
> IHostEnvironment
> IConfiguration

source:https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection?view=aspnetcore-3.1

**Comment by pengweiqhca** [comment]
override CreateHostBuilder

**Comment by pengweiqhca** [comment]
https://github.com/pengweiqhca/Xunit.DependencyInjection#how-to-inject-iconfiguration-or-ihostingenvironment-into-startup

**Comment by dirkesquire** [comment]
I found the README a bit unclear, but the code that worked for me in the end is as follows:

```
protected override IHostBuilder CreateHostBuilder(AssemblyName assemblyName) =>
    base.CreateHostBuilder(assemblyName)
        .ConfigureServices((context, services) => ConfigureServices(services, context.Configuration))
        .ConfigureHostConfiguration(builder => builder.AddInMemoryCollection(new Dictionary<string, string> { { HostDefaults.ApplicationKey, assemblyName.Name! } }));
```

also replace your ConfigureServices(IServiceCollection services) method with:


```
protected void ConfigureServices(IServiceCollection services, IConfiguration configuration)
{
    // ... 
}
```

**Comment by dirkesquire** [comment]
By the way, the above doesn't work very well. It doesn't read the same appsettings.json for some reason.

So I found that just creating your own configuration from scratch is easier and then you have full control over it:

```
var environmentName = Environment.GetEnvironmentVariable("Hosting:Environment");
var configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .AddJsonFile($"appsettings.{environmentName}.json", true)
    .AddEnvironmentVariables()
    .Build();
```

**Comment by pengweiqhca** [comment]
> By the way, the above doesn't work very well. It doesn't read the same appsettings.json for some reason.
> 
> So I found that just creating your own configuration from scratch is easier and then you have full control over it:
> 
> ```
> var environmentName = Environment.GetEnvironmentVariable("Hosting:Environment");
> var configuration = new ConfigurationBuilder()
>     .AddJsonFile("appsettings.json")
>     .AddJsonFile($"appsettings.{environmentName}.json", true)
>     .AddEnvironmentVariables()
>     .Build();
> ```

You can use `ConfigureHostConfiguration` or `ConfigureHostConfiguration` method

**Comment by pengweiqhca** [comment]
https://github.com/pengweiqhca/Xunit.DependencyInjection#how-to-configure-iconfiguration

**Comment by RockRockWhite** [comment]
I've read <How to configure IConfiguration>,however,I don't know exactly how can I make it.
Could you please write a example with more details.(Just a newer.)

**Comment by WeihanLi** [comment]
There's a sample project, you can have a look hope it would help <https://github.com/WeihanLi/XunitDependencyInjection.Samples/blob/main/P1_GetStarted/ConfigurationUsage/Startup.cs>

**Comment by RockRockWhite** [comment]
> There's a sample project, you can have a look hope it would help https://github.com/WeihanLi/XunitDependencyInjection.Samples/blob/main/P1_GetStarted/ConfigurationUsage/Startup.cs

Get it. Thank you so much.

**Comment by RockRockWhite** [comment]
> There's a sample project, you can have a look hope it would help https://github.com/WeihanLi/XunitDependencyInjection.Samples/blob/main/P1_GetStarted/ConfigurationUsage/Startup.cs

It helps.
