### ISSUE TITLE
README is out of date

### ISSUE THREAD

**Issue by dirkesquire** [pengweiqhca/Xunit.DependencyInjection#14]
The Readme.md is out of date, because the example code contains:

```protected override void ConfigureServices(IServiceCollection services)```

however this method doesn't exist in DependencyInjectionTestFramework class, and seems to have been replaced with:

```protected override void Configure(IServiceProvider provider)```

IServiceProvider doesn't have a method for .AddTransient, so its a bit unclear on how this library works anymore. Can the Readme be updated please?

**Comment by dirkesquire** [comment]
I should add that that I'm getting the error message:

```'Startup.ConfigureServices(IServiceCollection)': no suitable method found to override [My.Project.Test]```

**Comment by dirkesquire** [comment]
I did figure it out eventually by referring to the source code in Startup.cs.
Consider still updating the README.md though with this update :)

**Comment by pengweiqhca** [comment]
Thanks, I has updated. https://github.com/pengweiqhca/Xunit.DependencyInjection/commit/88640381806c2889c37a02044ecb97d6733025be
