### ISSUE TITLE
Update to 6.0 removed the protected virtual void ConfigureServices(IServiceCollection services)

### ISSUE THREAD

**Issue by luizfbicalho** [pengweiqhca/Xunit.DependencyInjection#15]
I updated to the 6.0 version and I got the error:

`Error	CS0115	'Startup.ConfigureServices(IServiceCollection)': no suitable method found to override	Even.Medicoes.TesteUnitario	C:\ProjetosGIT\Medicoes\Even.Medicoes.TesteUnitario\Startup.cs	29	Active
`
Is there a example on how to update to this version?

**Comment by pengweiqhca** [comment]
https://github.com/pengweiqhca/Xunit.DependencyInjection#how-to-use
