### ISSUE TITLE
System.TypeLoadException

### ISSUE THREAD

**Issue by rollibolly** [pengweiqhca/Xunit.DependencyInjection#16]
I'm getting the following exception while trying to run the unit tests:

`Method 'UseServiceProviderFactory' in type 'Microsoft.Extensions.Hosting.HostBuilder' from assembly 'Microsoft.Extensions.Hosting, Version=2.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation.`

Source: `protected override IHostBuilder CreateHostBuilder(AssemblyName assemblyName) =>
            base.CreateHostBuilder(assemblyName)
                .ConfigureServices(ConfigureServices);`

**Comment by rollibolly** [comment]
Issue solved with installing Microsoft.Extensions.Hosting package.

**Comment by danielleiszen** [comment]
Very nice. That should be in the documentation....
