### ISSUE TITLE
Xunit.DependencyInjection causes conflict in using Microsoft.Extensions.Configuration.Abstractions

### ISSUE THREAD

**Issue by Arash-Sabet** [pengweiqhca/Xunit.DependencyInjection#17]
This issue has become a roadblock to upgrade our nuget packages. 

> Microsoft.Extensions.Configuration.Abstractions, Version=3.1.3.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' which has a higher version than referenced assembly 'Microsoft.Extensions.Configuration.Abstractions' with identity 'Microsoft.Extensions.Configuration.Abstractions, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60

Please upgrade this package to 3.1.3.0 to address this problem. Further info:

![image](https://user-images.githubusercontent.com/26050123/81220037-ae535600-8fae-11ea-8938-1e76cbc20ebc.png)

**Comment by danielmeza** [comment]
Do this package need the 3.1.2 Configuration? why not to keep this package at 2.1.x? This will let out all project using 2.x version.

**Comment by pengweiqhca** [comment]
> Do this package need the 3.1.2 Configuration? why not to keep this package at 2.1.x? This will let out all project using 2.x version.

Because he installed `Microsoft.Extensions.Configuration` 3.1.2, rather than `Xunit.DependencyInjection` dependency, you don't have to worry about

**Comment by danielmeza** [comment]
Of course!
