### ISSUE TITLE
Supports of Xunit.Extensions.AssemblyFixture [https://github.com/JDCain/Xunit.Extensions.AssemblyFixture]

### ISSUE THREAD

**Issue by vabic** [pengweiqhca/Xunit.DependencyInjection#24]
I already have installed Xunit.Extensions.AssemblyFixture to my project for running tests in parallel. 
How documentation of Xunit.Extensions.AssemblyFixture suggests i added:
 [assembly: TestFramework(AssemblyFixtureFramework.TypeName, AssemblyFixtureFramework.AssemblyName)].
Everything is OK. All tests run in parallels. 

After I wanted to use IoC and installed Xunit.DependencyInjection with a Startup.cs (like your example) with my dependencies. On build i have error:
C:\XXX\XXX\MyProjectTest\MyProjectTest.AssemblyInfo.cs(14,12,14,31): error CS0579: Duplicate 'Xunit.TestFramework' attribute
Head of AssemblyInfo.cs:
`//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: Xunit.TestFramework("Xunit.DependencyInjection.DependencyInjectionTestFramework", "Xunit.DependencyInjection")]
`

I use ASP.NET core 2.1.

Any suggestions how to fix it?

**Comment by pengweiqhca** [comment]
You don't need `AssemblyFixture`, you only need to register it as singleton
