### ISSUE TITLE
Duplicate 'Xunit.TestFramework' attribute

### ISSUE THREAD

**Issue by jmevel** [pengweiqhca/Xunit.DependencyInjection#26]
Hello,

I'm trying to use this package however I get a compile error `CS0579: Duplicate 'Xunit.TestFramework' attribute` in the `TestProject/obj/Debug/netcoreapp3.1/TestProject.AssemblyInfo.cs` file

Here are the 2 lines responsible for this error:

```xml
[assembly: Xunit.TestFramework("Xunit.DependencyInjection.DependencyInjectionTestFramework", "Xunit.DependencyInjection")]
[assembly: Xunit.DependencyInjection.StartupType("TestProject.Startup")]
```

I'm using SpecFlow so I have 3 other references to xUnit Nuget packages:

> xunit 2.4.1
>
> SpecFlow.xUnit 3.4.3
>
> xunit.runner.visualstudio 2.4.3

Note that I don't have any `Startup` class in my test project so I don't really know what `TestProject.Startup` refers to.
I do have another class called ` DefaultWebAppFactory : WebApplicationFactory<Startup>` but I don't know where to setup the Nuget package to use this class as the *startup*...

I can I solve this compile error? 
I really would like to get dependency injected services into my xUnit classes.
SpecFlow.xUnit allows to do that but there're some tests I want to write without using Gherkins scenarios.

Thank you

**Comment by pengweiqhca** [comment]
This is v7 [new features](https://github.com/pengweiqhca/Xunit.DependencyInjection#v7-new-features).

**Comment by luizfbicalho** [comment]
I had one project that when I rebuild it the CS0579: Duplicate 'Xunit.TestFramework' attribute returns
I had to remove this project from the solution
How to make it stop?

**Comment by jmevel** [comment]
@pengweiqhca I installed the Nuget package version 7.0.2.
Just installing the package and doing nothing more gives a compile error so I guess this is not related to a v7 feature.

**Comment by pengweiqhca** [comment]
@jmevel @luizfbicalho You need modify your startup.
``` diff
-[assembly: TestFramework("Your.Test.Project.Startup", "Your.Test.Project")]

namespace Your.Test.Project
{
-   public class Startup : DependencyInjectionTestFramework
+   public class Startup
    {
-       public Startup(IMessageSink messageSink) : base(messageSink) { }

-       protected void ConfigureServices(IServiceCollection services)
+       public void ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<IDependency, DependencyClass>();
        }

-       protected override IHostBuilder CreateHostBuilder() =>
-           base.CreateHostBuilder(assemblyName)
-               .ConfigureServices(ConfigureServices);

-       protected override void Configure(IServiceProvider provider)
+       public void Configure(IServiceProvider provider)
    }
}
```

**Comment by jmevel** [comment]
As I told you I was using your Nuget version 7.0.2 which is therefore version 7 and your documentation says

> ## V7 new features
>
> - Don't need to add the assembly attribute TestFramework.
>
> - Startup does not need to inherit DependencyInjectionTestFramework.
>
> - Configure method support multiple parameters, like asp.net core Startup.

Moreover I also told you that I don't have any Startup in my test project because a test project doesn't start like a regular Web project (please read my very first message).

I reported you this issue, now you do what you want with this information. Feel free to close this ticket if you don't want to investigate this bug. 

In my case I solved my problem in another way so I don't need DI in my test classes anymore.

Regards,
Jérôme

**Comment by pengweiqhca** [comment]
> As I told you I was using your Nuget version 7.0.2 which is therefore version 7 and your documentation says
> 
> > ## V7 new features
> > 
> > * Don't need to add the assembly attribute TestFramework.
> > * Startup does not need to inherit DependencyInjectionTestFramework.
> > * Configure method support multiple parameters, like asp.net core Startup.
> 
> Moreover I also told you that I don't have any Startup in my test project because a test project doesn't start like a regular Web project (please read my very first message).
> 
> I reported you this issue, now you do what you want with this information. Feel free to close this ticket if you don't want to investigate this bug.
> 
> In my case I solved my problem in another way so I don't need DI in my test classes anymore.
> 
> Regards,
> Jérôme

Oh, I am sorry. I think the `SpecFlow.xUnit` alse generate `Xunit.TestFramework`, the `Xunit.TestFramework` must be unique, you have made a choice.

**Comment by kirk-marple** [comment]
Ran into this as well, and was able to solve it by adding these lines in a <PropertyGroup> in my .csproj:

`        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>  
`

**Comment by djpruitt** [comment]
Is there a work around for this issue? I am running into the same problem.

**Comment by pengweiqhca** [comment]
> Is there a work around for this issue? I am running into the same problem.

You should reference similar packages.

**Comment by GasparViannaSage** [comment]
I think the problem, as stated previously, is that the Specflow.XUnit also generate the Xunit.TestFramework...
So far I was also unable to make it work, it is not hard to test yourself, just try to add the package Specflow.XUnit and then the problems start ...

**Comment by increddibelly** [comment]
confirmed. I use specflow.xunit and xunit.dependencyinjection; I've been juggling versions for an hour, but none of the combinations work (and it shouldn't be this complicated to get working in the first place)

Wouldn't it be a quick fix to only add the attribute if it doesn't exist yet?

**Comment by pengweiqhca** [comment]
> confirmed. I use specflow.xunit and xunit.dependencyinjection; I've been juggling versions for an hour, but none of the combinations work (and it shouldn't be this complicated to get working in the first place)
> 
> Wouldn't it be a quick fix to only add the attribute if it doesn't exist yet?

<PropertyGroup>
  <EnableXunitDependencyInjectionDefaultTestFrameworkAttribute>false</EnableXunitDependencyInjectionDefaultTestFrameworkAttribute>
</PropertyGroup>
