### ISSUE TITLE
Why Xunit.DependencyInjection/Xunit.DependencyInjection/DependencyInjectionTestFramework.cs CreateExecutor is sealed

### ISSUE THREAD

**Issue by luizfbicalho** [pengweiqhca/Xunit.DependencyInjection#3]
Why CreateExecutor is marked as sealed.

I want to change the Dependency Injection container for example, and load some plugin dlls, 

The ideal is to separate this method in two 

Create host builder and create executor, this way we could add funcionality to the host builder before the create executor method.

**Comment by pengweiqhca** [comment]
https://github.com/pengweiqhca/Xunit.DependencyInjection/commit/e1cde22e8837f5aad70473a3d63d98a4ab3893bd
https://www.nuget.org/packages/Xunit.DependencyInjection/5.1.0

**Comment by luizfbicalho** [comment]
Nice, thanks
