### ISSUE TITLE
Support for xbehave extension

### ISSUE THREAD

**Issue by Eklange** [pengweiqhca/Xunit.DependencyInjection#32]
**Is your feature request related to a problem? Please describe.**
I'm using .net core 3.1 xunit test project with xunit.dependencyinjection. I would like to use xBehave extension with xunit.dependencyinjection and right now they are not compatible. What I can see and understand scenario tag is not working and steps are never executed. Everything works if I uninstall xunit.dependencyinjection.

**Describe the solution you'd like**
Support for xBehave so that steps are executed and shown in test runner.

**Describe alternatives you've considered**
Replace one of the extensions to get a combination that is compatible with each other.

**Additional context**
Example from https://github.com/adamralph/xbehave.net

[Scenario]
        public void Addition(int x, int y, Calculator calculator, int answer)
        {
            // NOTE: This method should only contain step definitions.
            // It doesn't make sense to write any code outside them.
            // (See the note below under "Steps".)

            "Given the number 1"
                .x(() => x = 1);

            "And the number 2"
                .x(() => y = 2);

            "And a calculator"
                .x(() => calculator = new Calculator());

            "When I add the numbers together"
                .x(() => answer = calculator.Add(x, y));

            "Then the answer is 3"
                .x(() => answer.Should().Be(3));
        }

**Comment by pengweiqhca** [comment]
I did not use [xbehave.net](https://github.com/adamralph/xbehave.net), maybe you should commit new issure in [xbehave.net](https://github.com/adamralph/xbehave.net)
