### ISSUE TITLE
How to add a json configuration file?

### ISSUE THREAD

**Issue by arisliang** [pengweiqhca/Xunit.DependencyInjection#37]
In aspnetcore project, we have access to `IConfigurationBuilder`, which has `AddJsonFile` to add a json as configuration. How do we achieve the same here? To add a json configuration file.

**Comment by WeihanLi** [comment]
You can inject configuration by `ConfigureHost` method in Startup, there's a simple sample project <https://github.com/WeihanLi/XunitDependencyInjection.Samples/blob/main/P1_GetStarted/ConfigurationUsage/Startup.cs#L18>

``` csharp
 public void ConfigureHost(IHostBuilder hostBuilder)
 {
     hostBuilder
         .ConfigureHostConfiguration(builder =>
         {
             builder.AddJsonFile("appsettings.json");
         });
 }
```

**Comment by arisliang** [comment]
it works, thanks!
