### ISSUE TITLE
How to get the service without DI?

### ISSUE THREAD

**Issue by arisliang** [pengweiqhca/Xunit.DependencyInjection#38]
For some reason, if have to use service locator to get the instance of a service. Can we do that?

E.g. through something like `ServiceProvider.GetService`?

**Comment by WeihanLi** [comment]
You can get the `IServiceProvider` by adding `IServiceProvider` parameter for the `Configure` method in the `Startup`, just like follows:

``` csharp
public void Configure(IServiceProvider serviceProvider)
{
    ServiceLocator.SetServiceProvider(serviceProvider);
}
```

**Comment by pengweiqhca** [comment]
> You can get the `IServiceProvider` by adding `IServiceProvider` parameter for the `Configure` method in the `Startup`, just like follows:
> 
> ```cs
> public void Configure(IServiceProvider serviceProvider)
> {
>     ServiceLocator.SetServiceProvider(serviceProvider);
> }
> ```

Or use [a custom ServiceProviderFactory ](https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/master/Xunit.DependencyInjection.Test/Startup.cs#L13).

**Comment by arisliang** [comment]
What is the `ServiceLocator` in this case? Do we need to declare it somewhere?

**Comment by arisliang** [comment]
I've put the `public static IServiceProvider ServiceProvider;` in startup class, and reference it from where it's needed. Work like a charm! Thanks.

**Comment by Devqon** [comment]
Sorry to reply on this old thread, but I was in need of the same thing and this didn't work for me. I always get the exception that the `IServiceProvider` is already disposed off:

Startup.cs
```csharp
public static IServiceProvider ServiceProvider { get; private set; }

public void ConfigureServices(IServiceCollection services)
{
    services.AddScoped<IMyService, MyService>();
    // ..
}

public void Configure(IServiceProvider serviceProvider)
{
    ServiceProvider = serviceProvider;
}
```

MyClass.cs
```
public void DoSomething()
{
    // throws exception "Cannot access a disposed object.\r\nObject name: 'IServiceProvider'."
    Startup.ServiceProvider.GetService<IMyService>();
}
```

Am I missing something?

**Comment by pengweiqhca** [comment]
`public void Configure(IServiceProvider serviceProvider)` the serviceProvider is scoped.

**Comment by Devqon** [comment]
@pengweiqhca so what you're saying is that the service locator is not possible? Because the only way I can think of is using the `IServiceProvider` directly, but if it is disposed it is not possible.

My use-case is that I use AutoFixture to generate testdata, which also uses a 'store' to retrieve settings from a json configuration file. Therefore I need register all customizations through DI, and register those in the `AutoDataAttribute` of AutoFixture.

Something like this:

MyCustomization.cs
```csharp
public class MyCustomization : ICustomization
{
    private readonly TestSettings _testSettings;
    public MyCustomization(TestSettings testSettings) => _testSettings = testSettings;

    public void Customize(IFixture fixture) =>fixture.Custmize<TestUser>(c => c.Password, _testSettings.TestUserPassword);
}
```

Startup.cs
```csharp
public class Startup
{
    public void ConfigureService(IServiceCollection services)
    {
        // .. register Configuration through json etc.

        var settings = new TestSettings();
        new ConfigureFromConfigurationOptions<TestSettings>(configuration.GetSection("TestSettings")).Configure(settings);
        services.AddSingleton<TestSettings>(settings);

        services.AddTransient<ICustomization, MyCustomization>();
    }
}
```

GenerateTestDataAttribute.cs
```csharp
public class GenerateTestDataAttribute : AutoDataAttribute
{
    public GenerateTestDataAttribute() : base(FixtureFactory) {}

    private static IFixture FixtureFactory()
    {
        var fixture = new Fixture();
        // This does not work, ServiceProvider is disposed
        foreach (var customization in Startup.ServiceProvider.GetServices<ICustomization>())
        {
            fixture.Customize(customization);
        }
    }
}
```

**Comment by Devqon** [comment]
I have found a really dirty workaround by checking out the code in this library. I noticed there was a `TheoryTestCaseDataContext` which has a reference to the `IServiceProvider` in a static manner, so I created this ugly piece of reflection code:

```csharp
internal class ServiceLocator
{
    private readonly IServiceProvider _serviceProvider;
    private ServiceLocator(IServiceProvider serviceProvider) => _serviceProvider = serviceProvider;

    public ServiceLocator Current => new ServiceLocator(GetServiceProvider());

    public TService GetService<TService>() => _serviceProvider.GetService<TService>();

    private static IServiceProvider GetServiceProvider()
    {
        var assembly = Assembly.GetAssembly(typeof(MethodDataAttribute));
        var type = assembly.GetType("Xunit.DependencyInjection.TheoryTestCaseDataContext");
        var serviceProviderProperty = type.GetProperty("Services");
        var provider = (IServiceProvider) serviceProviderProperty.GetValue(type, null);
        return provider;
    }
}
```

Of course with some big warnings in it. Hope it helps someone else!
