### ISSUE TITLE
当项目名与命名空间不一致时，导致无法注入

### ISSUE THREAD

**Issue by Varorbc** [pengweiqhca/Xunit.DependencyInjection#39]
当项目名与命名空间不一致时，导致无法注入

**Comment by WeihanLi** [comment]
可以参考 README <https://github.com/pengweiqhca/Xunit.DependencyInjection#how-to-find-startup>

假如项目名是 `Your.Test.Project`，Startup 默认是  `Your.Test.Project.Startup, Your.Test.Project`.
如果不一致可以通过在项目文件里自定义  `XunitStartupAssembly` and `XunitStartupFullName` 来自定义 Startup
``` xml
<Project>
  <PropertyGroup>
    <XunitStartupAssembly>Abc</XunitStartupAssembly>
    <XunitStartupFullName>Xyz</XunitStartupFullName>
  </PropertyGroup>
</Project>
```
| XunitStartupAssembly | XunitStartupFullName | Startup |
| ------- | ------ | ------ |
|   |   | Your.Test.Project.Startup, Your.Test.Project |
| Abc |   | Abc.Startup, Abc |
|   | Xyz | Xyz, Your.Test.Project |
| Abc | Xyz | Xyz, Abc |

**Comment by Varorbc** [comment]
谢谢
