### ISSUE TITLE
ITestOutputHelperAccessor Null in Configure

### ISSUE THREAD

**Issue by Harab7** [pengweiqhca/Xunit.DependencyInjection#44]
**In Startup File**
When Inject <code>ITestOutputHelperAccessor</code> Output has null value

Steps:
1. Written Custom BaseClass For More Configurations
2. Startup has inherited BaseClass
3. CustomTestClass has inherited Startup

But <code>ITestOutputHelperAccessor</code> has null !.

**Screenshots**
![image](https://user-images.githubusercontent.com/30981174/128313948-554cfb6e-c1d9-4571-9700-1b86886338d7.png)

 - Net5
 - Xunit 2.4.1
 - Xunit.DependencyInjection 7.3.0

**Comment by pengweiqhca** [comment]
Can yout give me a demo?

**Comment by WeihanLi** [comment]
I think it's because the `ITestOutputHelperAccessor` where you use is not in a test case, so the `Output` is null,
it likes `HttpContext` in ASP.NET Core, you can get the `HttpContext` from `IHttpContextAccessor` only when there's a request, you can get the `ITestOutputHelper` only when there's a test case.

**Comment by Harab7** [comment]
> I think it's because the `ITestOutputHelperAccessor` where you use is not in a test case, so the `Output` is null,
> it likes `HttpContext` in ASP.NET Core, you can get the `HttpContext` from `IHttpContextAccessor` only when there's a request, you can get the `ITestOutputHelper` only when there's a test case.

but i check with breakpoint before test executed in test in `Configure` method this null. this code worked in other project

**Comment by Harab7** [comment]
Upon closer inspection, I realized that although the data in this section is null, it is still injected! I do not know how strange it was; Anyway, my problem was not with this part, although the data was null, it was a problem of my own program
