### ISSUE TITLE
Error in .net core 3 preview 6

### ISSUE THREAD

**Issue by luizfbicalho** [pengweiqhca/Xunit.DependencyInjection#6]
I'm having this exception after the update do preview 6 (I'm not sure if preview 5 was ok, I jumped some updates)

 Message: 
    System.AggregateException : One or more errors occurred. (Method not found: 'Microsoft.Extensions.Hosting.IHostingEnvironment Microsoft.Extensions.Hosting.HostBuilderContext.get_HostingEnvironment()'.) (The following constructor parameters did not have matching fixture data: PermissaoController controller)
    ---- System.MissingMethodException : Method not found: 'Microsoft.Extensions.Hosting.IHostingEnvironment Microsoft.Extensions.Hosting.HostBuilderContext.get_HostingEnvironment()'.
    ---- The following constructor parameters did not have matching fixture data: PermissaoController controller
  Stack Trace: 
    at ----- Inner Stack Trace #1 (System.MissingMethodException) -----
    at HostBuilder.BuildAppConfiguration()
    at HostBuilder.Build()
    at ----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----

this is my test

`public class PermissaoControllerTest
    {
        public PermissaoControllerTest(PermissaoController controller)
        {
            Controller = controller;
        }

        public PermissaoController Controller { get; }
        [Fact]
        public async void Task_Add_Permissao_Return_OkResult()
        {
            //Arrange  
            var post = await Controller.Create(CancellationToken.None);
            post.Descricao = "Teste";

            //Act  
            var data = await Controller.Post(post,CancellationToken.None);

            //Assert  
            Assert.IsType<OkObjectResult>(data);
        }

        [Fact]
        public async void Task_Add_Permissao_Return_BadRequest()
        {
            //Arrange  

            var post = await Controller.Create(CancellationToken.None);

            //Act  
            var data = await Controller.Post(post, CancellationToken.None);

            //Assert  
            Assert.IsType<BadRequestResult>(data);
        }
    }`

Do you need any aditional information?

**Comment by luizfbicalho** [comment]
I changed to receive IServiceProvider and still got the same error

**Comment by pengweiqhca** [comment]
Updated. [Xunit.DependencyInjection 5.4.0](https://www.nuget.org/packages/Xunit.DependencyInjection/5.4.0)

**Comment by luizfbicalho** [comment]
To make it work I had to copy from github source and paste inside my project, without any change.

Thanks
