### ISSUE TITLE
.NET 6 support for new minimal hosting model

### ISSUE THREAD

**Issue by J05HM0N5TER** [pengweiqhca/Xunit.DependencyInjection#62]
**Describe the bug**
When using the [new minimal hosting model](https://docs.microsoft.com/en-us/aspnet/core/migration/50-to-60?view=aspnetcore-6.0&tabs=visual-studio#new-hosting-model) I keep getting error `Error Message:
   System.InvalidOperationException : Can't load type [project_namespace].Tests.Startup in '[project_namespace].Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'`. This is using an asp.net webapi. I have yet to try this in a new project, I just wanted to report this workaround in case anyone else in encountering the same thing. I migrated this project from .net 5, but I don't think that would affect anything. This is not completely guaranteed that it is this package casing this issue, if it is not feel free to close this issue.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new project using the new model (without Startup class) 
2. Try to dependency inject using this package.

**Expected behaviour**
It dependency injects as normal

**Workaround** 
Adding 
```csharp
namespace [project_namespace].Tests
{
	public class Startup { }
}
```
 inside Program.cs makes it work

**Comment by pengweiqhca** [comment]
You need create xunit test project.

**Comment by J05HM0N5TER** [comment]
I don't understand what you mean. Are you saying I need to create a new project? The project I was talking about what a unit test project using xunit if that is what you are talking about.

**Comment by pengweiqhca** [comment]
The minimal api project is asp.net core 6+ project, not test project. If you want write test case, you need create a test project.

**Comment by J05HM0N5TER** [comment]
Oh. I was having trouble with Startup.cs not doing anything after I updated to .net 6. So I assumed that I needed to update it to use the minimal hosting model, since this is the same things that happened to my asp.net projects. That was probably my fault, I'll try to fix it. Thanks for the help.

**Comment by J05HM0N5TER** [comment]
Do you want me to rename this issue to something else since this was not what I thought it was?

**Comment by pengweiqhca** [comment]
Not necessary
