### ISSUE TITLE
Cannot remove default IXunitTestCaseRunnerWrappers 

### ISSUE THREAD

**Issue by jlarke-bunnings** [pengweiqhca/Xunit.DependencyInjection#63]
**Describe the bug**
The library does not provide any way to remove the default `IXunitTestCaseRunnerWrapper` instances:
`DependencyInjectionTestCaseRunnerWrapper` and `DependencyInjectionTheoryTestCaseRunnerWrapper`.

Both are registered *after* the user's `Startup.ConfigureServices` call has run, meaning they cannot be removed from the `ServiceCollection`. I am using another XUnit framework (LightBDD) that implements its own test runner, however the default adapter picks up any class extending `XunitTestRunner` and overrides its behaviour.

Implementing a custom wrapper is not feasible, as I still want the constructor arguments to be resolved by dependency injection, I just want to skip the default runner wrappers.

**Expected behavior**
I would expect the internal `ConfigureServices` to be called *before* the user's `Startup.ConfigureServices`, so that it can modify any default registrations before the host is built.

**Comment by pengweiqhca** [comment]
Your can implement `IXunitTestCaseRunnerWrapper` and register it.
``` C#
public class TestCaseRunnerWrapper : IXunitTestCaseRunnerWrapper
{
    public virtual Type TestCaseType => typeof(XunitTestCase);

    public Task<RunSummary> RunAsync(IXunitTestCase testCase, IServiceProvider provider, IMessageSink diagnosticMessageSink, IMessageBus messageBus, object?[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) =>
        new XunitTestCaseRunner(testCase, testCase.DisplayName,
            testCase.SkipReason, constructorArguments, testCase.TestMethodArguments,
            messageBus, aggregator, cancellationTokenSource).RunAsync();
}

public class TheoryTestCaseRunnerWrapper : IXunitTestCaseRunnerWrapper
{
    public virtual Type TestCaseType => typeof(XunitTheoryTestCase);

    public Task<RunSummary> RunAsync(IXunitTestCase testCase, IServiceProvider provider, IMessageSink diagnosticMessageSink, IMessageBus messageBus, object?[] constructorArguments, ExceptionAggregator aggregator, CancellationTokenSource cancellationTokenSource) =>
        new XunitTheoryTestCaseRunner(testCase, testCase.DisplayName,
            testCase.SkipReason, constructorArguments, diagnosticMessageSink, messageBus,
            aggregator, cancellationTokenSource).RunAsync();
}
```
``` C#
services.TryAddEnumerable(ServiceDescriptor.Singleton<IXunitTestCaseRunnerWrapper, TestCaseRunnerWrapper>());
services.TryAddEnumerable(ServiceDescriptor.Singleton<IXunitTestCaseRunnerWrapper, TheoryTestCaseRunnerWrapper>());
```

**Comment by jlarke-bunnings** [comment]
@pengweiqhca Thanks for replying.

Correct me if I'm wrong, but the `constructorArguments` passed to these wrappers will not have had their `DelayArgument` parameters resolved will they? From what I could see in the code, that only happens after the wrappers on this line:

https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/d843d6923701fcbc9a0da1aecfe3bf53bb45c962/Xunit.DependencyInjection/DependencyInjectionTestMethodRunner.cs#L78

And `CreateTestClassConstructorArguments` is `protected static internal` so I can't call it from my own wrapper to resolve them. The `DelayArgument` type is also `internal` so I can't even copy-paste the `CreateTestClassConstructorArguments` method into my own code without using reflection.

**Comment by pengweiqhca** [comment]
[8.4.0](https://www.nuget.org/packages/Xunit.DependencyInjection/8.4.0)

**Comment by harish-venkataramanan-cko** [comment]
@jlarke-bunnings Could you please share how made LightBDD and this library to work in conjunction? It is still unclear how LightBDD can start using the services registered using this library. It will be really helpful for many, thanks 🙏
