### ISSUE TITLE
Missing License Information in NuGet Package Metadata

### ISSUE THREAD

**Issue by wsugarman** [pengweiqhca/Xunit.DependencyInjection#64]
**Describe the bug**
The current NuGet packages, like [`Xunit.DependencyInjection` v8.4.0](https://www.nuget.org/packages/Xunit.DependencyInjection/), are missing the license information.

**To Reproduce**
Looking at the NuGet.org portal for the packages, you'll notice that lack of license metadata. You can also download the nupkg file, unzip it, and inspect the nuspec file.

**Expected behavior**
Packages should include license information for discoverability and to aid any tooling.

**Screenshots**
## Xunit.DependencyInjection
![image](https://user-images.githubusercontent.com/2955179/159605866-d2f2e250-2c3b-446b-a809-0cf4a4077858.png)

vs

## Newtonsoft.Json
![image](https://user-images.githubusercontent.com/2955179/159606037-aea28bbf-8ce1-4947-9045-a7d019b3225a.png)

**Comment by pengweiqhca** [comment]
Thanks.
