### ISSUE TITLE
Support Xunit.StaFact package

### ISSUE THREAD

**Issue by stany9g** [pengweiqhca/Xunit.DependencyInjection#66]
**Is your feature request related to a problem? Please describe.**
I am using this package for running some of my test cases in different thread https://github.com/AArnott/Xunit.StaFact I have noticed that when use Xunit.DependencyInjection these attributes gets "ignored" and the Thread state is always MTA.

**Describe the solution you'd like**
It would be awesome if these attributes would be supported

**Describe alternatives you've considered**
Not sure yet

**Additional context**
I am doing integration tests in WPF application.

Thank you for considering.

**Comment by pengweiqhca** [comment]
Package [Xunit.DependencyInjection.StaFact](https://www.nuget.org/packages/Xunit.DependencyInjection.StaFact).

**Comment by stany9g** [comment]
Thank you so much for implementing this feature.

**Comment by pengweiqhca** [comment]
@stany9g I have updated xUnit to v3. Please help me verif [Xunit.DependencyInjection.StaFact](https://www.nuget.org/packages/Xunit.DependencyInjection.StaFact/10.0.0-preview.1)
