### ISSUE TITLE
Log scope to test output

### ISSUE THREAD

**Issue by carlin-q-scott** [pengweiqhca/Xunit.DependencyInjection#68]
**Is your feature request related to a problem? Please describe.**
I use logger scopes to add call stack context to all my log messages, but that information isn't output to the XUnit test log.

**Describe the solution you'd like**
I'd like the XunitTestOutputLogger to work like the standard console logger which appends the logger scope to the end of the output message.

**Describe alternatives you've considered**
Forking the logger in this project to add this feature.

**Comment by owns** [comment]
You can see [here](https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/main/Xunit.DependencyInjection.Logging/XunitTestOutputLogger.cs#L35) there's just a dummy nullable instance added.
Looking at [Microsoft's default implementation](https://source.dot.net/#Microsoft.Extensions.Logging/Logger.cs,106), it doesn't look *too hard*, but I've never personally used scopes.

**Comment by pengweiqhca** [comment]
I have refactored Xunit.DependencyInjection.Logging and support log scope.
