### ISSUE TITLE
Startup is not run when running multiple tests classes

### ISSUE THREAD

**Issue by xnoreq** [pengweiqhca/Xunit.DependencyInjection#69]
I have a Startup class that sets a static class property in the Startup's ConfigureServices method.

My test project contains two test classes that access this property. Running each class (through VS test runner) separately is fine.
But running the entire project makes the second project fail.

Debugging Startup.ConfigureServices shows that it is not run between after the last test of the first test class.

**Comment by pengweiqhca** [comment]
Please provide demo code.
