### ISSUE TITLE
Example has ConfigureServices as returning IServiceProvider. But base class returns void

### ISSUE THREAD

**Issue by douglasg14b** [pengweiqhca/Xunit.DependencyInjection#7]
Readme example override:

```cs
        protected override IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<IDependency, DependencyClass>();

            return services.BuildServiceProvider();
        }
```

Base class (DependencyInjectionTestFramework):

![image](https://user-images.githubusercontent.com/1400380/61915049-a6cb3080-aef7-11e9-8de8-f758fee2ed10.png)

Error:

![image](https://user-images.githubusercontent.com/1400380/61915062-b2b6f280-aef7-11e9-8030-c087d9b6ec31.png)

**Comment by pengweiqhca** [comment]
Thank your feedback, I has updated
