### ISSUE TITLE
Can't load type Tests.Startup

### ISSUE THREAD

**Issue by ikjelle** [pengweiqhca/Xunit.DependencyInjection#70]
I got this error:
```
[xUnit.net 00:00:01.23]     Tests.Test1 [FAIL]
  Failed Tests.Test1 [1 ms]
  Error Message:
   System.InvalidOperationException : Can't load type Tests.Startup in 'Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
```
Apparently you can easily fix this by creating a class called Startup under the namespace Tests, i.e.:
```c#
namespace Tests { class Startup { } }
```

But I feel like this isn't an intended requirement or at least should be mentioned in the README.

### More info
I tried step 1-3 in **How to find Startup?** and they only work if I have a Startup class in namespace Tests. Otherways I keep getting that error. (but maybe step 4 works)

Tests.csproj
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xunit.DependencyInjection" Version="8.6.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
```

**Comment by pengweiqhca** [comment]
Has mentioned in the [README](https://github.com/pengweiqhca/Xunit.DependencyInjection#how-to-use).

**Comment by ikjelle** [comment]
``` c#
namespace Your.Test.Project
{
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddTransient<IDependency, DependencyClass>();
        }
    }
}
```
Is this what you mean? 
Because this doesn't tell me, that I am REQUIRED to have a startup class at the ROOT-level of the test project. (But maybe I am reading it wrong)

**Comment by zeroClearAmerican** [comment]
Experiencing the same issue. If there is not a Startup file in the root of the project then the error "_Can't load type Project.Startup_" is thrown for all of my tests. 

> I tried step 1-3 in How to find Startup? and they only work if I have a Startup class in namespace Tests. Otherways I keep getting that error. (**but maybe step 4 works**)

Tested method 4, [the Global Startup](https://github.com/pengweiqhca/Xunit.DependencyInjection#4-global-startup), by specifying the below lines in my .csproj file: 
```
        <PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<IsPackable>false</IsPackable>
		<XunitStartupAssembly>Project</XunitStartupAssembly>
		<XunitStartupFullName>Startup2</XunitStartupFullName>
	</PropertyGroup>
```

And got this error:
> System.InvalidOperationException : Can't load type Startup2 in 'Project, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'

So it appears a Startup class in the root of the project is REQUIRED as a workaround at the moment. 

@pengweiqhca your previous response is too vague. Can you clarify if the REQUIRED Startup in the project root is intended? All of the methods described in the "[How to find Startup?](https://github.com/pengweiqhca/Xunit.DependencyInjection#how-to-find-startup)" section except for "[3. Closest Startup > _4. Startup_](https://github.com/pengweiqhca/Xunit.DependencyInjection#3-closest-startup)" are broken.

**Comment by pengweiqhca** [comment]
@zeroClearAmerican I updated document and [modify code(8.7.0)](https://www.nuget.org/packages/Xunit.DependencyInjection/8.7.0), [allow missing default startup in some case](https://github.com/pengweiqhca/Xunit.DependencyInjection#4-default-startup) now. If have any question, please reply to me.

**Comment by zeroClearAmerican** [comment]
All 4 methods outlined in the README appear to be working properly now. Thanks for the quick response!
