### ISSUE TITLE
Host Logic is not Hit During Test Discovery

### ISSUE THREAD

**Issue by cmeyertons** [pengweiqhca/Xunit.DependencyInjection#72]
**Describe the bug**
My understanding is test discovery runs in a separate process than the actual tests themselves.  If you have data-driven Theories that are dependent on the host (e.g. you are populating available test cases from a database table, etc), they do not get properly discovered in that first discovery process

**To Reproduce**
Create a theory data class that is statically dependent on the Host

```csharp
public class MyTheoryData: TheoryData<object>
{
   // in constructor pull in some static reference that is initialized during host build out
  // leveraging assumption that host is built before test data is discovered / executed
}
```
1. During discovery, the theory will be discovered but its underlying test cases will not.
2. During execution, the underlying tests are ran fine (because the host got built), but they all end up all nested / mangled under the top level theory.

**Expected behavior**
I would expect the discovery and execution behavior to be the same 

**Additional context**
Based on my limited understanding of the codebase, It appears you are overriding the execution behavior of the Xunit Framework, but not the discovery behavior in the [DependencyInjectionTestFramework](https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/main/Xunit.DependencyInjection/DependencyInjectionTestFramework.cs)

I would love to help contribute, but I can't get the solution to build locally due to my corporate laptop having net461 removed and MS doesn't appear to have the targeting pack working

**Comment by pengweiqhca** [comment]
Maybe you can use [MethodData](https://github.com/pengweiqhca/Xunit.DependencyInjection#memberdata-how-to-inject)

**Comment by cmeyertons** [comment]
That still doesn’t help during the discovery phase I’m pretty sure. 

Would you like me to create a repro project in a fork?

**Comment by pengweiqhca** [comment]
I saw the [TheoryData usecase](https://andrewlock.net/creating-strongly-typed-xunit-theory-test-data-with-theorydata/), [MethodData](https://github.com/pengweiqhca/Xunit.DependencyInjection#memberdata-how-to-inject)  can resolve your problem.

``` C#
public class MyTheoryData : TheoryData<object>
{
    public MyTheoryData(IServiceA service) { ]
}
```
=>
``` C#
public static IEnumerator<object[]> MyTheoryData(IServiceA service) { }
```
