### ISSUE TITLE
How do I add middlewares?

### ISSUE THREAD

**Issue by hartmark** [pengweiqhca/Xunit.DependencyInjection#73]
I'm having this Configure-method:
```

    public void Configure(ILoggerFactory loggerFactory, ITestOutputHelperAccessor accessor, IApplicationBuilder app)
    {
        loggerFactory.AddProvider(
            new XunitTestOutputLoggerProvider(accessor, (_, _) => true));
            
        app.UseCorrelationId();
    }
```

I get this error:
```
System.AggregateException: One or more errors occurred. (No service for type 'Microsoft.AspNetCore.Builder.IApplicationBuilder' has been registered.) ...
```

How do I properly inject IApplicationBuilder so I can use the CorrelationId middleware?

**Comment by hartmark** [comment]
I get the same error, here's my Full Startup.cs
```

public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddLogging(logging => { logging.SetMinimumLevel(LogLevel.Trace); });
    }

    public void Configure(ILoggerFactory loggerFactory, ITestOutputHelperAccessor accessor , IApplicationBuilder app)
    {
        loggerFactory.AddProvider(
            new XunitTestOutputLoggerProvider(accessor, (_, _) => true));

        app.UseMiddleware<MyMiddleware>();
    }
    
    public void ConfigureHost(IHostBuilder hostBuilder) =>
        hostBuilder.ConfigureWebHostDefaults(webHostBuilder => webHostBuilder
            .UseTestServer()
            .UseStartup<Startup>());
}
```

**Comment by pengweiqhca** [comment]
`.UseStartup<Startup>()`, the `Startup` is not test project Startup class, it must be asp.net core project Startup class.

**Comment by pengweiqhca** [comment]
https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/main/Xunit.DependencyInjection.Test.AspNetCore/Startup.cs

**Comment by hartmark** [comment]
Thanks for the example, I'm trying to get the logging working. This following example shows no output:
```
public class AspNetCoreStartup
{
    public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory, ITestOutputHelperAccessor accessor, ILogger<AspNetCoreStartup> logger)
    {
        loggerFactory.AddProvider(
            new XunitTestOutputLoggerProvider(accessor, (_, _) => true));

        logger.LogDebug("In Configure");
        app.UseCorrelationId();

        app.Run(context =>
        {
            logger.LogDebug("In run");
            return context.Response.WriteAsync(TestServerTest.Key + context.Request.Headers.ToJson(true));
        });
    }

    public void ConfigureServices(IServiceCollection services)
    {
        services.AddLogging(logging =>
        {
            logging.SetMinimumLevel(LogLevel.Trace);
        });
    }
}
```

**Comment by hartmark** [comment]
How was this completed?

**Comment by pengweiqhca** [comment]
What are you want to output?

**Comment by hartmark** [comment]
Sorry for late response, I have been on holiday.

I have created a small reproducing repo.
https://github.com/hartmark/xunit-dependency-test

I set a breakpoint here and debug the test and it breaks as expected:
https://github.com/hartmark/xunit-dependency-test/blob/d31d5bfd535a3ddd65025e54b5966976e49727d2/AspNetCoreStartup.cs#L14

Line 17 doesn't get printed out in the test.

Also, how do I get the block on line 22-23 to run, no breakpoint will trigger there.

**Comment by pengweiqhca** [comment]
Thanks feedback this issue, I resolved in this [commit](https://github.com/pengweiqhca/Xunit.DependencyInjection/commit/461a08c90a6ddf48e29510243385058a8d93ecc9).

But I found some issue in you sample:
1. Some repeated code in Startup and AspNetCoreStartup
2. [app.Run](https://github.com/hartmark/xunit-dependency-test/blob/d31d5bfd535a3ddd65025e54b5966976e49727d2/AspNetCoreStartup.cs#L22) func not invoke, because you not call http request.

**Comment by hartmark** [comment]
Cool, I peeked in your repo and were able to get it working now.

There are some minor issues left.

I have pushed an update with my latest fixes for my repo

* The logger doesn't print out anything lower than Information.
https://github.com/hartmark/xunit-dependency-test/blob/177e916fc662a703004d4262571a9b89f34954d3/TestHost.cs#L34
This line doesn't show in the output, I have setup it to not filter the log at:
https://github.com/hartmark/xunit-dependency-test/blob/f700f070820429b5d8450bcc690236bed58c1f5e/Startup.cs#L25

* Logging done in AspNetCoreStartup.Configure is not shown, this line is never logged:
  https://github.com/hartmark/xunit-dependency-test/blob/f700f070820429b5d8450bcc690236bed58c1f5e/Startup.cs#L32

**Comment by pengweiqhca** [comment]
1. You also configure Microsoft.Extension.Logging minimum level.
2. `Configure` is called before the test is executed, this feature only work in test case.

**Comment by hartmark** [comment]
Alright I can live with number 2. How do I fix 1?

**Comment by pengweiqhca** [comment]
https://learn.microsoft.com/en-us/dotnet/core/extensions/logging?tabs=command-line#default-log-level

**Comment by hartmark** [comment]
Cool, I'm all good now, thanks for all help!
