### ISSUE TITLE
Mixed Startup.cs levels not clear in inheritenence when using multiple methods (ConfigureHost/ConfigureServices)

### ISSUE THREAD

**Issue by Relki** [pengweiqhca/Xunit.DependencyInjection#76]
This is a suggestion for this repositories instructions in the code section. When showing how the startup.cs inheritance works from class level and checks each level back to root of project, should mention that if you specify you can't mix Startup.cs/ConfigureServices on class namespace level, and use a Statup.cs/ConfigureHost on the root level. Both have to be in the same Startup.cs file in the same level you want to use it in.

This took me a bit to figure out and was wondering my my IConfigurion wasn't being injected when set up in root/Statup.cs/ConfigureHost but was using class level Startup.cs/ConfigureServices.

**Comment by pengweiqhca** [comment]
Yes, can't mix multi startup class except [integration with asp.net core](https://github.com/pengweiqhca/Xunit.DependencyInjection#integration-aspnet-core-testhost30), but you can do it via inherit base startup implement.
