### ISSUE TITLE
Can't execute more than one Fact per TestClass

### ISSUE THREAD

**Issue by franramvel** [pengweiqhca/Xunit.DependencyInjection#78]
When using an injected instance, it only works for one fact but it throws Error: The following constructor parameters did not have matching fixture data for the other.

**To Reproduce**
1. Add a Service in Startup,cs
2. Inject it in UnitTestClass constructor
3. Declare two or more facts that use it

**Expected behavior**
Use the injected service across all the facts in the class

**Screenshots**
![image](https://user-images.githubusercontent.com/78751805/223606539-e3a88338-d2e6-4125-9bcc-563d3696d87b.png)
![image](https://user-images.githubusercontent.com/78751805/223606654-b20750bf-9daf-4e98-ac8f-2b7fda443f20.png)
![image](https://user-images.githubusercontent.com/78751805/223606760-b164410d-7c66-495d-95a8-dc3f0849c0a5.png)

**Additional context**
The two facts in the example contains the same exact logic
Tested with AddTransient, AddSingleton and AddScoped
.NET 7

**Comment by pengweiqhca** [comment]
`dotnet test` result?
