### ISSUE TITLE
How does this interact with IClassFixture?

### ISSUE THREAD

**Issue by douglasg14b** [pengweiqhca/Xunit.DependencyInjection#8]
Say I have a test class with a IClassFixture of the same type as what is configured in my dependency injection. I also have a dependency that relies on this type to be either injected, or used as a provider:

**Test Class:** `MyTestsClass : IClassFixture<SqliteTestFixture>`. 

**DI Config:** `services.AddScoped<SqliteTestFixture>();`

**DI Config that relies on `SqliteTestFixture`:** `services.AddTransient<TestDbContext>(x => x.GetRequiredService<SqliteTestFixture>().Context);`

________________________________________

**Expected Behavior:**

* `MyTestsClass` receives only one instance
*  Only one instance of `SqliteTestFixture` is instantiated

**Unknown Behaviors:**

* Who/what creates the instance? 
* Does the `ServiceProvider` build one instance, and `xUnit` build another? Or does this plugin sort that out so olny one instance is instantiated for that test class?
* Is the same instance that it injected into `MyTestsClass` the same instance that is used as a provider for `TestDbContext`?

________________________________________

**Observed Behavior:**

* Two instances of `SqliteTestFixture` are instantiated before I see it used
* `TestDbContext` is resolved using the *2nd* `SqliteTestFixture` instance
  * Any dependencies that need a `TestDbContext`, receive one from this fixture instance
* `MyTestsClass` receives *only the first* `SqliteTestFixture` instance for each test case
  * My test class will receive and use the 1st instance only
*  A new `SqliteTestFixture` instance is instantiated before each test case (Yet my class only receives the first one)

_________________________________________

This creates issues when I need a test class to only receive one instance of a `SqliteTestFixture`, but I can't have that as a singleton, since it will persist across all test classes. But I also have dependencies that need DbContexts provided by `SqliteTestFixture`. As soon as a different `SqliteTestFixture` starts provided DbContexts, that creates a new Sqlite DB, separate from the rest. Which breaks tests....

The jist here is that `IClassFixture` used in conjunction with DI with this library should only provide the instance created by xUnit, and should only use that instance for dependency resolving.

Can you add clarification, and explanation on this?

**Comment by pengweiqhca** [comment]
IClassFixture is xunit's feature

**Comment by douglasg14b** [comment]
@pengweiqhca  Sorry if I wasn't very clear.

If this has no interaction with xUnit or `IClassFixture`, how difficult would it be for such an integration to be made to avoid DI conflicts?

**Comment by douglasg14b** [comment]
Alternatively, if the DI could be configured on a per-collection or per-class basis instead of a per-assembly basis that would also eliminate this problem.

**Comment by pengweiqhca** [comment]
You can review this [line code](https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/master/Xunit.DependencyInjection/DependencyInjectionTestClassRunner.cs#L48), `ClassFixtureMappings` before DI
