### ISSUE TITLE
Use Default loglevel for Xunit.DependencyInjection.Logging

### ISSUE THREAD

**Issue by carlin-q-scott** [pengweiqhca/Xunit.DependencyInjection#82]
**Describe the bug**
The XunitTestOutputLoggerProvider does not use the configured Default logging level. It instead defaults to Information.

**To Reproduce**
Create a test Startup.cs as described in the readme and set the minimum log level to debug:
```c#
    public class Startup
    {
        public IHostBuilder CreateHostBuilder() => Program.CreateHostBuilder()
            .ConfigureLogging(logging => logging.SetMinimumLevel(LogLevel.Debug));

        public void Configure(ILoggerFactory loggerFactory, ITestOutputHelperAccessor accessor) =>
            loggerFactory.AddProvider(new XunitTestOutputLoggerProvider(accessor));
    }
```

**Expected behavior**
ILogger.LogDebug() calls should show up in the test logs.

**Workaround**
Modify Startup.cs to override the logging filter for the xunit logger:
```c#
        public void Configure(ILoggerFactory loggerFactory, ITestOutputHelperAccessor accessor) =>
            loggerFactory.AddProvider(new XunitTestOutputLoggerProvider(accessor,
                (source, ll) => ll >= LogLevel.Debug));
```

**Comment by pengweiqhca** [comment]
Sorry, I updated the README.

**Comment by carlin-q-scott** [comment]
Thanks @pengweiqhca , but can the implementation be updated to not filter out any log messages by default?

**Comment by pengweiqhca** [comment]
@marklauter And you should configure Microsoft.Extensions.Logging minimum level.

**Comment by pengweiqhca** [comment]
@carlin-q-scott @marklauter Upgrade `Xunit.DependencyInjection.Logging` to 8.1.0 and use `services.AddLogging(lb => lb.AddXunitOutput())`;
