### ISSUE TITLE
Expose Output property on ITestOutputHelper

### ISSUE THREAD

**Issue by marklauter** [pengweiqhca/Xunit.DependencyInjection#84]
**Is your feature request related to a problem? Please describe.**
It seems like a violation of encapsulation to have to expose the underlying implementation of ITestOutputHelper by requiring a cast to TestOutputHelper in order to access the Output property.

**Describe the solution you'd like**
It would be nice if ITestOutputHelper exposed the Output property so the cast can be avoided.

**Describe alternatives you've considered**
I'm currently casting like this.
```c#
var stdout = ((Xunit.Sdk.TestOutputHelper)this.output).Output;
```

**Additional context**
Maybe I'm doing it wrong?

Also, I love the Xunit.DI package. Thank you for providing it to the community.

**Comment by pengweiqhca** [comment]
`ITestOutputHelper` is an xUnit interface. Perhaps you can expose `Output` through an extension method.
