### ISSUE TITLE
Document how to use with WebApplicationFactory

### ISSUE THREAD

**Issue by goldsam** [pengweiqhca/Xunit.DependencyInjection#86]
Please document how to use this library along with [`WebApplicationFactory`](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0#sut-environment)

**Comment by pengweiqhca** [comment]
Sorry, I have rarely used `WebApplicationFactory` and I need to research to know if and how to integrate.

**Comment by WeihanLi** [comment]
`WebApplicationFactory` is based on the test server

I'd like to suggest using the test server directly, hope these two samples would help

- https://github.com/pengweiqhca/Xunit.DependencyInjection/blob/main/test/Xunit.DependencyInjection.Test.AspNetCore/Startup.cs
- https://github.com/WeihanLi/XunitDependencyInjection.Samples/blob/main/P4_TestServer/TestServerIntegration/Startup.cs

**Comment by goldsam** [comment]
My primary use case for `WebApplicationFactory` is to bootstrap an application written using top-level statements such as [this one taken from the docs](https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio#examine-the-code). 

This approach would adhere to the [open-closed principle](https://en.wikipedia.org/wiki/Open%E2%80%93closed_principle) by allowing dependencies to be overridden without requiring the application's code be modified. The alternative I see is to use a Startup class in the main app, however it seems this is a legacy approach with newer projects moving towards top-level statements.

What are your thoughts and opinions?

**Comment by goldsam** [comment]
@pengweiqhca  I didn't mean to close this issue. Can you reopen it please?

**Comment by WeihanLi** [comment]
I add a MinimalAPI sample here https://github.com/WeihanLi/XunitDependencyInjection.Samples/tree/main/P6_MinimalAPI
hope it would help

**Comment by goldsam** [comment]
@WeihanLi The issue with this approach is that the unit tests and the web application each have their own distinct dependency injection containers. To allow the web application to log to the unit test log output I had to inject the `ILoggerProvider` from the test environment into the web application as follows:

```csharp
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Logging;

namespace MinimalApiTest;

public sealed class TestWebApplicationFactory: WebApplicationFactory<Program>
{
    private readonly ILoggerProvider _loggerProvider;

    public TestWebApplicationFactory(ILoggerProvider loggerProvider)
    {
        _loggerProvider = loggerProvider;
    }
    protected override IWebHostBuilder? CreateWebHostBuilder()
    {
        builder.ConfigureTestServices(services => services.AddSingleton(_loggerProvider));

        return base.CreateWebHostBuilder();
    }
}
```

While this does technically work, it gets to be cumbersome and potentially error-prone when you want to inject additional services shared by both your tests and the web application under test. I don't see this approach as being viable.

**Comment by pengweiqhca** [comment]
If you want [Integration with WebApplicationFactory](https://github.com/pengweiqhca/Xunit.DependencyInjection#integration-with-webapplicationfactory), you can use `XunitWebApplicationFactory`. If you just want to integrate logs, you should use [`MartinCostello.Logging.XUnit`](https://github.com/martincostello/xunit-logging).

**Comment by pengweiqhca** [comment]
[Asp.Net Core MinimalApi](https://github.com/pengweiqhca/Xunit.DependencyInjection#minimalapi)

**Comment by mrmartan** [comment]
How are these samples using `WebApplicationFactory` ?
