### ISSUE TITLE
Per-test Container Setup

### ISSUE THREAD

**Issue by dustinlacewell** [pengweiqhca/Xunit.DependencyInjection#9]
It would be pretty handy if we were able to setup the container bindings on a per-test basis.

**Comment by pengweiqhca** [comment]
Per-test class or per-test case?

**Comment by dustinlacewell** [comment]
![image](https://user-images.githubusercontent.com/53952/63657359-84326e80-c766-11e9-9418-8f5b5a6bda19.png)

**Comment by pengweiqhca** [comment]
You can use [Fixtures](https://xunit.net/docs/shared-context)
