### ISSUE TITLE
Version 8.9.0 breaking change with SkippableFact

### ISSUE THREAD

**Issue by jstcyr** [pengweiqhca/Xunit.DependencyInjection#95]
**Describe the bug**
Following the upgrade to version 8.9.0, our XUnit AssemblyRunner started invoking OnTestFailed when a test was skipped with XUnit.DependencyInjection.SkippableFact 8.0.1. It was working fine with version 8.8.2.

**Expected behavior**
Skipped test should not fail the test.

**Additional context**
The test suite runs in a docker image based on ubuntu focal.

**Comment by pengweiqhca** [comment]
Can you provide more details? Such as failure output.

**Comment by jstcyr** [comment]
I don't have the xUnit output, but here is the TestFailedInfo we receive from xUnit.
`{
	"ExceptionType": "Xunit.SkipException",
	"ExceptionMessage": "Test skipping",
	"ExceptionStackTrace": "   at Xunit.Skip.If(Boolean condition, String reason)\n   at <testPath>() in /app/src/<testfile>.cs:line 57\n   at Xunit.DependencyInjection.DependencyInjectionTestInvoker.AsyncStack(Task task, Activity activity)",
	"ExecutionTime": 0.0846403,
	"Output": "",
	"TypeName": "<TestClass>",
	"MethodName": "<TestName>",
	"Traits": {
		"AlertPriority": [
			"P4"
		],
	},
	"TestDisplayName": "<FullTestName>",
	"TestCollectionDisplayName": "<Collection>",
	"$type": "TestFailedInfo"
}`

**Comment by WeihanLi** [comment]
@jstcyr  maybe better with a code snippet to reproduce the error

**Comment by jstcyr** [comment]
I added a sample app reproducing an error here:
[Repository](https://github.com/jstcyr/SkippableFactSample)

**Comment by pengweiqhca** [comment]
@jstcyr Sorry, I forget to release packages. Please upgrade `Xunit.DependencyInjection.SkippableFact` to 8.1.0.
